import type { RegistrationWithDetails, RegistrationStatus } from '@/types/database';

const MOCK_REGISTRATIONS: RegistrationWithDetails[] = [
  {
    id: 'reg-001',
    family_id: 'fam-001',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-001',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 4 sessões (50€)',
    unit_price: 50,
    num_sessions: 4,
    num_children: 1,
    total_price: 50,
    selected_dates: ['8 (manhã)', '15 (manhã)', '22 (manhã)', '29 (manhã)'],
    status: 'pendente',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: null,
    notes: 'Alergia a amendoim. Primeiro contacto com a natureza.',
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-01T09:00:00Z',
    updated_at: '2026-06-01T09:00:00Z',
    family: {
      id: 'fam-001',
      parent_name: 'Ana Sofia Mendes',
      email: 'ana.mendes@gmail.com',
      phone: '+351 912 345 678',
      created_at: '2026-06-01T09:00:00Z',
    },
    children: [
      { id: 'child-001', registration_id: 'reg-001', name: 'Pedro Mendes', date_of_birth: '2023-03-15' },
    ],
  },
  {
    id: 'reg-002',
    family_id: 'fam-002',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-002',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 16 sessões + 32 registos fotográficos (264€)',
    unit_price: 264,
    num_sessions: 16,
    num_children: 2,
    total_price: 264,
    selected_dates: ['1 (manhã)', '8 (tarde)', '15 (manhã)', '22 (tarde)', '29 (manhã)', '29 (tarde)'],
    status: 'pago_confirmado',
    image_consent: 'Sim, autorizo',
    has_photos: true,
    voucher_code: 'FLORESTA10',
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-02T10:30:00Z',
    updated_at: '2026-06-05T14:00:00Z',
    family: {
      id: 'fam-002',
      parent_name: 'Carlos Silva',
      email: 'carlos.silva@outlook.pt',
      phone: '+351 963 210 987',
      created_at: '2026-06-02T10:30:00Z',
    },
    children: [
      { id: 'child-002', registration_id: 'reg-002', name: 'Maria Silva', date_of_birth: '2021-07-20' },
      { id: 'child-003', registration_id: 'reg-002', name: 'João Silva', date_of_birth: '2019-11-03' },
    ],
  },
  {
    id: 'reg-003',
    family_id: 'fam-003',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-003',
    month: 'julho',
    year: 2026,
    plan: '2 sessões + 6 registos fotográficos (40€)',
    unit_price: 40,
    num_sessions: 2,
    num_children: 1,
    total_price: 40,
    selected_dates: ['5 (manhã)', '19 (manhã)'],
    status: 'a_pagar',
    image_consent: 'Não autorizo',
    has_photos: true,
    voucher_code: null,
    notes: null,
    nif: '234 567 890',
    invoice_requested: true,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-03T08:15:00Z',
    updated_at: '2026-06-03T08:15:00Z',
    family: {
      id: 'fam-003',
      parent_name: 'Maria João Ferreira',
      email: 'mjoao.ferreira@sapo.pt',
      phone: '+351 934 567 891',
      created_at: '2026-06-03T08:15:00Z',
    },
    children: [
      { id: 'child-004', registration_id: 'reg-003', name: 'Sofia Ferreira', date_of_birth: '2022-05-08' },
    ],
  },
  {
    id: 'reg-004',
    family_id: 'fam-004',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-004',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 8 sessões + 16 registos fotográficos (132€)',
    unit_price: 132,
    num_sessions: 8,
    num_children: 1,
    total_price: 132,
    selected_dates: ['3 (manhã)', '10 (manhã)', '17 (manhã)', '24 (manhã)'],
    status: 'pendente',
    image_consent: 'Sim, autorizo',
    has_photos: true,
    voucher_code: null,
    notes: null,
    nif: '256 789 012',
    invoice_requested: true,
    webhook_error: true,
    webhook_error_message: 'Timeout ao tentar contactar o endpoint do Brevo. Retentar.',
    created_at: '2026-06-04T11:00:00Z',
    updated_at: '2026-06-04T11:00:00Z',
    family: {
      id: 'fam-004',
      parent_name: 'Rui Nuno Figueiredo',
      email: 'rui.figueiredo@gmail.com',
      phone: '+351 919 876 543',
      created_at: '2026-06-04T11:00:00Z',
    },
    children: [
      { id: 'child-005', registration_id: 'reg-004', name: 'Beatriz Figueiredo', date_of_birth: '2020-09-25' },
    ],
  },
  {
    id: 'reg-005',
    family_id: 'fam-005',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-005',
    month: 'julho',
    year: 2026,
    plan: '1 sessão (14€)',
    unit_price: 14,
    num_sessions: 1,
    num_children: 1,
    total_price: 14,
    selected_dates: ['12 (tarde)'],
    status: 'pago_confirmado',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: null,
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-04T14:20:00Z',
    updated_at: '2026-06-06T09:00:00Z',
    family: {
      id: 'fam-005',
      parent_name: 'Inês Cardoso',
      email: 'ines.cardoso@hotmail.com',
      phone: '+351 966 543 210',
      created_at: '2026-06-04T14:20:00Z',
    },
    children: [
      { id: 'child-006', registration_id: 'reg-005', name: 'Tomás Cardoso', date_of_birth: '2023-01-14' },
    ],
  },
  {
    id: 'reg-006',
    family_id: 'fam-006',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-006',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 4 sessões (50€)',
    unit_price: 50,
    num_sessions: 4,
    num_children: 2,
    total_price: 100,
    selected_dates: ['7 (manhã)', '14 (manhã)', '21 (manhã)', '28 (manhã)'],
    status: 'lembrete',
    image_consent: 'Apenas para uso interno',
    has_photos: false,
    voucher_code: null,
    notes: 'Criança mais nova ainda a adaptar-se ao grupo.',
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-05T09:45:00Z',
    updated_at: '2026-06-10T12:00:00Z',
    family: {
      id: 'fam-006',
      parent_name: 'Patrícia Lopes',
      email: 'patricia.lopes@gmail.com',
      phone: '+351 937 654 321',
      created_at: '2026-06-05T09:45:00Z',
    },
    children: [
      { id: 'child-007', registration_id: 'reg-006', name: 'Leonor Lopes', date_of_birth: '2021-04-30' },
      { id: 'child-008', registration_id: 'reg-006', name: 'Martim Lopes', date_of_birth: '2023-08-12' },
    ],
  },
  {
    id: 'reg-007',
    family_id: 'fam-007',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-007',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 8 sessões (88€)',
    unit_price: 88,
    num_sessions: 8,
    num_children: 1,
    total_price: 88,
    selected_dates: ['2 (manhã)', '9 (manhã)', '16 (manhã)', '23 (manhã)'],
    status: 'a_pagar',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: 'VERÃO20',
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-06T10:00:00Z',
    updated_at: '2026-06-06T10:00:00Z',
    family: {
      id: 'fam-007',
      parent_name: 'Francisco Rocha',
      email: 'francisco.rocha@netcabo.pt',
      phone: '+351 912 111 222',
      created_at: '2026-06-06T10:00:00Z',
    },
    children: [
      { id: 'child-009', registration_id: 'reg-007', name: 'Gabriel Rocha', date_of_birth: '2020-02-18' },
    ],
  },
  {
    id: 'reg-008',
    family_id: 'fam-008',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-008',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 16 sessões (176€)',
    unit_price: 176,
    num_sessions: 16,
    num_children: 1,
    total_price: 176,
    selected_dates: ['1 (manhã)', '1 (tarde)', '8 (manhã)', '8 (tarde)', '15 (manhã)', '15 (tarde)', '22 (manhã)', '22 (tarde)'],
    status: 'pago_confirmado',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: null,
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-06T16:30:00Z',
    updated_at: '2026-06-08T10:00:00Z',
    family: {
      id: 'fam-008',
      parent_name: 'Teresa Almeida',
      email: 'teresa.almeida@gmail.com',
      phone: '+351 961 333 444',
      created_at: '2026-06-06T16:30:00Z',
    },
    children: [
      { id: 'child-010', registration_id: 'reg-008', name: 'Afonso Almeida', date_of_birth: '2019-06-05' },
    ],
  },
  {
    id: 'reg-009',
    family_id: 'fam-009',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-009',
    month: 'julho',
    year: 2026,
    plan: '2 sessões (26€)',
    unit_price: 26,
    num_sessions: 2,
    num_children: 1,
    total_price: 26,
    selected_dates: ['6 (tarde)', '20 (tarde)'],
    status: 'cancelado',
    image_consent: 'Não autorizo',
    has_photos: false,
    voucher_code: null,
    notes: 'Cancelou por férias no estrangeiro.',
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-07T08:00:00Z',
    updated_at: '2026-06-12T11:00:00Z',
    family: {
      id: 'fam-009',
      parent_name: 'Hugo Monteiro',
      email: 'hugo.monteiro@sapo.pt',
      phone: null,
      created_at: '2026-06-07T08:00:00Z',
    },
    children: [
      { id: 'child-011', registration_id: 'reg-009', name: 'Matilde Monteiro', date_of_birth: '2022-10-01' },
    ],
  },
  {
    id: 'reg-010',
    family_id: 'fam-010',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-010',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 4 sessões (50€)',
    unit_price: 50,
    num_sessions: 4,
    num_children: 1,
    total_price: 50,
    selected_dates: ['4 (manhã)', '11 (manhã)', '18 (manhã)', '25 (manhã)'],
    status: 'pendente',
    image_consent: 'Apenas para uso interno',
    has_photos: false,
    voucher_code: null,
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-08T09:20:00Z',
    updated_at: '2026-06-08T09:20:00Z',
    family: {
      id: 'fam-010',
      parent_name: 'Luísa Barros',
      email: 'luisa.barros@vodafone.pt',
      phone: '+351 938 765 432',
      created_at: '2026-06-08T09:20:00Z',
    },
    children: [
      { id: 'child-012', registration_id: 'reg-010', name: 'Rodrigo Barros', date_of_birth: '2021-12-20' },
    ],
  },
  {
    id: 'reg-011',
    family_id: 'fam-011',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-011',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 8 sessões + 16 registos fotográficos (132€)',
    unit_price: 132,
    num_sessions: 8,
    num_children: 1,
    total_price: 132,
    selected_dates: ['5 (tarde)', '12 (tarde)', '19 (tarde)', '26 (tarde)'],
    status: 'pago_confirmado',
    image_consent: 'Sim, autorizo',
    has_photos: true,
    voucher_code: null,
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-09T13:00:00Z',
    updated_at: '2026-06-11T09:30:00Z',
    family: {
      id: 'fam-011',
      parent_name: 'Susana Pinto',
      email: 'susana.pinto@gmail.com',
      phone: '+351 915 222 333',
      created_at: '2026-06-09T13:00:00Z',
    },
    children: [
      { id: 'child-013', registration_id: 'reg-011', name: 'Alice Pinto', date_of_birth: '2020-08-14' },
    ],
  },
  {
    id: 'reg-012',
    family_id: 'fam-012',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-012',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 4 sessões (50€)',
    unit_price: 50,
    num_sessions: 4,
    num_children: 1,
    total_price: 50,
    selected_dates: ['3 (tarde)', '10 (tarde)', '17 (tarde)', '24 (tarde)'],
    status: 'a_pagar',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: null,
    notes: 'Prefere sessões da tarde.',
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-10T10:45:00Z',
    updated_at: '2026-06-10T10:45:00Z',
    family: {
      id: 'fam-012',
      parent_name: 'Diogo Cunha',
      email: 'diogo.cunha@iol.pt',
      phone: '+351 964 444 555',
      created_at: '2026-06-10T10:45:00Z',
    },
    children: [
      { id: 'child-014', registration_id: 'reg-012', name: 'Margarida Cunha', date_of_birth: '2022-03-07' },
    ],
  },
  {
    id: 'reg-013',
    family_id: 'fam-013',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-013',
    month: 'julho',
    year: 2026,
    plan: '1 sessão (14€)',
    unit_price: 14,
    num_sessions: 1,
    num_children: 1,
    total_price: 14,
    selected_dates: ['11 (manhã)'],
    status: 'cancelado',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: null,
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-11T08:30:00Z',
    updated_at: '2026-06-15T14:00:00Z',
    family: {
      id: 'fam-013',
      parent_name: 'Vera Sousa',
      email: 'vera.sousa@gmail.com',
      phone: '+351 913 555 666',
      created_at: '2026-06-11T08:30:00Z',
    },
    children: [
      { id: 'child-015', registration_id: 'reg-013', name: 'Simão Sousa', date_of_birth: '2023-06-22' },
    ],
  },
  {
    id: 'reg-014',
    family_id: 'fam-014',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-014',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 4 sessões (50€)',
    unit_price: 50,
    num_sessions: 4,
    num_children: 1,
    total_price: 50,
    selected_dates: ['2 (tarde)', '9 (tarde)', '16 (tarde)', '23 (tarde)'],
    status: 'pendente',
    image_consent: 'Sim, autorizo',
    has_photos: false,
    voucher_code: null,
    notes: null,
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-12T11:15:00Z',
    updated_at: '2026-06-12T11:15:00Z',
    family: {
      id: 'fam-014',
      parent_name: 'Nuno Oliveira',
      email: 'nuno.oliveira@clix.pt',
      phone: '+351 939 777 888',
      created_at: '2026-06-12T11:15:00Z',
    },
    children: [
      { id: 'child-016', registration_id: 'reg-014', name: 'Constança Oliveira', date_of_birth: '2021-09-03' },
    ],
  },
  {
    id: 'reg-015',
    family_id: 'fam-015',
    month_id: null,
    submitted_at: null,
    tally_submission_id:'tally-015',
    month: 'julho',
    year: 2026,
    plan: 'Pack mensal 8 sessões (88€)',
    unit_price: 88,
    num_sessions: 8,
    num_children: 1,
    total_price: 88,
    selected_dates: ['6 (manhã)', '13 (manhã)', '20 (manhã)', '27 (manhã)'],
    status: 'pago_confirmado',
    image_consent: 'Apenas para uso interno',
    has_photos: false,
    voucher_code: null,
    notes: 'Família muito participativa.',
    nif: null,
    invoice_requested: false,
    webhook_error: false,
    webhook_error_message: null,
    created_at: '2026-06-13T09:00:00Z',
    updated_at: '2026-06-16T10:00:00Z',
    family: {
      id: 'fam-015',
      parent_name: 'Catarina Matos',
      email: 'catarina.matos@gmail.com',
      phone: '+351 967 888 999',
      created_at: '2026-06-13T09:00:00Z',
    },
    children: [
      { id: 'child-017', registration_id: 'reg-015', name: 'Lourenço Matos', date_of_birth: '2019-04-17' },
    ],
  },
];

export function getRegistrations(
  month: string,
  year: number,
  status?: string
): RegistrationWithDetails[] {
  return MOCK_REGISTRATIONS.filter(
    (r) =>
      r.month === month &&
      r.year === year &&
      (status === undefined || status === 'todos' || r.status === status)
  );
}

export interface MonthStats {
  total: number;
  pendentes: number;
  pagos: number;
  expectedRevenue: number;
}

export function getMonthStats(month: string, year: number): MonthStats {
  const regs = getRegistrations(month, year);
  return {
    total: regs.length,
    pendentes: regs.filter((r) => r.status === 'pendente').length,
    pagos: regs.filter((r) => r.status === 'pago_confirmado').length,
    expectedRevenue: regs
      .filter((r) => r.status !== 'cancelado')
      .reduce((sum, r) => sum + r.total_price, 0),
  };
}

export interface StatusCounts {
  todos: number;
  pendente: number;
  a_pagar: number;
  lembrete: number;
  pago_confirmado: number;
  cancelado: number;
}

export function getStatusCounts(month: string, year: number): StatusCounts {
  const regs = getRegistrations(month, year);
  return {
    todos: regs.length,
    pendente: regs.filter((r) => r.status === 'pendente').length,
    a_pagar: regs.filter((r) => r.status === 'a_pagar').length,
    lembrete: regs.filter((r) => r.status === 'lembrete').length,
    pago_confirmado: regs.filter((r) => r.status === 'pago_confirmado').length,
    cancelado: regs.filter((r) => r.status === 'cancelado').length,
  };
}
